version: "3.1"

services:
  fastapi_server:
    build: .
    container_name: 'fastapi_mailing'
    entrypoint: "/entrypoint.sh"
    restart: always
    expose:
      - ${FASTAPI_PORT}
    ports:
      - ${FASTAPI_PORT}:${FASTAPI_PORT}
    volumes:
      - "./:/mailing"
    env_file:
      - .env
    depends_on:
      - mongodb

  mongodb:
    image: mongo:4.4.4-bionic
    ports:
      - "27017:27017"
    volumes:
      - ./mongo_data:/data/db

volumes:
  data_fastapi_mailing:
  mongo_data:
